# Site settings
title: University of Maryland
course_name: Bioinformatics Algorithms, Databases, and Tools
course_description: "This course will focus on algorithmic, and computational aspects of biological data analysis, and specifically on genomics."
course_semester: "Spring 2020"
description: |
    Instructor: Rob Patro

message: Register to our <a href="http://www.piazza.com/umd/spring2020/cmsc423">Piazza page</a> to get announcements via e-mail.
baseurl: "/CMSC423_S20" # the subpath of your site, e.g. /blog/
url: "https://rob-p.github.io/CMSC423_S20" # the base hostname & protocol for your site
# githubdir: "rob-p/CMSC858D"

# Author/user information
#email: instructor-last-name@iust.ac.ir
#twitter_username: username 
#github_username:  username
#authorurl: "http://author-url.com/page"
address: |
    Department of Computer Science
    University of Maryland
    College Park, MD

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
